app/account/urls.py
from django.urls import path

from account.views import ProfileView, UserSignUpView, UserActivateView


app_name = "account"

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate')
]

app/currency/api/urls.py
from rest_framework import routers

from currency.api.views import RateViewSet, ContactUsViewSet, SourceView

router = routers.SimpleRouter(trailing_slash=True)
router.register('rates', RateViewSet, basename='rate')
router.register('contactus', ContactUsViewSet, basename='contact-us')
router.register('source', SourceView, basename='source')

app_name = 'currency_api'
urlpatterns = router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (

    RateListView,
    RateCreateView,
    RateUpdateView,
    RateDeleteView,
    RateDetailsView,

    ContactUsListView,
    ContactUsCreateView,
    ContactUsUpdateView,
    ContactUsDeleteView,
    ContactUsDetailsView,

    SourceCreateView,
    SourceDeleteView,
    SourceUpdateView,
    SourceListView,
    SourceDetailsView,

)

app_name = "currency"

urlpatterns = [

    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailsView.as_view(), name='rate-details'),
    path("contactus/list/", ContactUsListView.as_view(), name='contactus-list'),
    path("contactus/create/", ContactUsCreateView.as_view(), name='contactus-create'),
    path("contactus/update/<int:pk>/", ContactUsUpdateView.as_view(), name='contactus-update'),
    path("contactus/delete/<int:pk>/", ContactUsDeleteView.as_view(), name='contactus-delete'),
    path("contactus/details/<int:pk>/", ContactUsDetailsView.as_view(), name='contactus-details'),
    path("source/create/", SourceCreateView.as_view(), name='source-create'),
    path("source/update/<int:pk>/", SourceUpdateView.as_view(), name='source-update'),
    path("source/delete/<int:pk>/", SourceDeleteView.as_view(), name='source-delete'),
    path("source/details/<int:pk>/", SourceDetailsView.as_view(), name='source-details'),
    path("source/list/", SourceListView.as_view(), name='source-list'),



]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from currency.views import IndexView

schema_view = get_schema_view(
   openapi.Info(
      title="Currency API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),

    path('auth/', include('django.contrib.auth.urls')),

    path('reset/password', include('django.contrib.auth.urls'), name='password_reset'),

    path('auth/', include('account.urls')),

    path('api/account/', include('account.api.urls')),

    path('api/currency/', include('currency.api.urls')),

    path('currency/', include('currency.urls')),

    path('', IndexView.as_view(), name='index'),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from django.db import models
from currency.choices import CurrencyTypeChoices
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static


def source_directory_path(instance, filename):
    return f'logo/source_{instance.source_name}/{filename}'


class Rate(models.Model):
    buy = models.DecimalField(_('Buy'), max_digits=10, decimal_places=2)
    sell = models.DecimalField(_('Sell'), max_digits=10, decimal_places=2)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    currency_type = models.SmallIntegerField(
        _('Currency type'),
        choices=CurrencyTypeChoices.choices,
        default=CurrencyTypeChoices.USD
    )
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')

    class Meta:
        verbose_name = _('Rate')
        verbose_name_plural = _('Rates')


class ContactUs(models.Model):
    contact_id = models.AutoField(primary_key=True)
    email_from = models.EmailField(_('Email from'), )
    subject = models.CharField(_('Subject'), max_length=255)
    message = models.TextField(_('Message'), max_length=2048)

    class Meta:
        verbose_name = _('Contact Us')
        verbose_name_plural = _('Contact Us')


class Source(models.Model):
    code_name = models.CharField(_('Code name'), max_length=64, unique=True)
    source_url = models.CharField(_('Source URL'), max_length=255, blank=False)
    source_name = models.CharField(_('Source name'), max_length=64, blank=False)
    logo = models.FileField(_('Logo'), default=None, null=True, blank=True, upload_to=source_directory_path)

    class Meta:
        verbose_name = _('Source')
        verbose_name_plural = _('Sources')

    def __str__(self):
        return self.source_name

    @property
    def logo_url(self) -> str:
        if self.logo:
            return self.logo.url

        return static('bank.png')


class RequestResponseTimeMiddlewareModel(models.Model):
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=20)
    execute_time = models.DecimalField(max_digits=5, decimal_places=4)

    class Meta:
        verbose_name = _('Log')
        verbose_name_plural = _('Logs')

app/currency/forms.py
from django import forms

from currency.models import Source, Rate, ContactUs


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = ('source_url', 'source_name', 'logo')


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = ('buy', 'sell', 'source', 'currency_type')


class ContactUsForm(forms.ModelForm):

    class Meta:
        model = ContactUs
        fields = ('email_from', 'subject', 'message')

app/currency/api/views.py
from django.core.cache import cache
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.decorators import action
from rest_framework.filters import OrderingFilter
from rest_framework import filters
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet

from currency.api.paginators import RatePagination
from currency.api.serializers import RateSerializer, ContactUsSerializer, SourceSerializer
from currency.api.throtling import RateThrottle
from currency.choices import CurrencyTypeChoices
from currency.constants import LATEST_RATES_CACHE_KEY
from currency.filters import RateFilter, ContactUsFilter, SourceFilter
from currency.models import Rate, ContactUs, Source


class RateViewSet(ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer
    pagination_class = RatePagination
    filterset_class = RateFilter
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
    )
    ordering_fields = ('buy', 'sell', 'created')
    throttle_classes = (RateThrottle,)
    permission_classes = (AllowAny,)

    @action(methods=('GET',), detail=False, serializer_class=RateSerializer)
    def latest(self, request, *args, **kwargs):
        cached_data = cache.get(LATEST_RATES_CACHE_KEY)
        if cached_data is not None:
            return Response(cached_data)

        sources = Source.objects.all()

        latest_rates = []
        for source in sources:
            for currency in CurrencyTypeChoices:
                rate = Rate.objects.filter(source=source, currency_type=currency).order_by('-created').first()

                if rate is not None:
                    latest_rates.append(RateSerializer(instance=rate).data)

        cache.set(LATEST_RATES_CACHE_KEY, latest_rates, 60 * 60 * 24 * 7)  # 1 week

        return Response(latest_rates)


class ContactUsViewSet(ModelViewSet):
    queryset = ContactUs.objects.all()
    serializer_class = ContactUsSerializer
    filterset_class = ContactUsFilter
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
        filters.SearchFilter,
    )
    ordering_fields = ('email_from', 'subject')
    search_fields = ('email_from', 'subject')


class SourceView(ReadOnlyModelViewSet):
    queryset = Source.objects.all()
    serializer_class = SourceSerializer
    filterset_class = SourceFilter
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
        filters.SearchFilter,
    )
    ordering_fields = ('source_name',)
    search_fields = ('source_name',)

app/currency/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView, DetailView
from django_filters.views import FilterView

from currency.filters import RateFilter, ContactUsFilter, SourceFilter
from currency.forms import SourceForm, RateForm, ContactUsForm
from currency.models import Rate, ContactUs, Source

from currency.tasks import send_email_in_background


# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'


class RateListView(FilterView):
    queryset = Rate.objects.all().select_related('source').order_by('-created')
    template_name = 'rate_list.html'
    paginate_by = 25
    filterset_class = RateFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_params'] = '&'.join(
            f'{key}={value}' for key, value in self.request.GET.items() if key != 'page'
        )
        return context


class RateCreateView(CreateView):
    form_class = RateForm
    template_name = 'rate_create.html'
    success_url = reverse_lazy('currency:rate-list')


class RateUpdateView(UserPassesTestMixin, UpdateView):
    model = Rate
    form_class = RateForm
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class RateDeleteView(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class RateDetailsView(LoginRequiredMixin, DetailView):
    model = Rate
    template_name = 'rate_details.html'
    success_url = reverse_lazy('currency:rate-list')


class ContactUsListView(FilterView):
    queryset = ContactUs.objects.all()
    template_name = 'contactUs.html'
    filterset_class = ContactUsFilter
    paginate_by = 25


class ContactUsCreateView(CreateView):
    form_class = ContactUsForm
    template_name = 'contactus_create.html'
    success_url = reverse_lazy('currency:contactus-list')

    def _send_email(self):
        subject = self.object.subject
        message = self.object.message
        email_from = self.object.email_from

        send_email_in_background.apply_async(
            kwargs={
                "subject": subject,
                "message": message,
                "email_from": email_from
            },
            countdown=10,
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_email()
        return redirect


class ContactUsUpdateView(UpdateView):
    model = ContactUs
    form_class = ContactUsForm
    template_name = 'contactus_update.html'
    success_url = reverse_lazy('currency:contactus-list')


class ContactUsDeleteView(DeleteView):
    model = ContactUs
    template_name = 'contactus_delete.html'
    success_url = reverse_lazy('currency:contactus-list')


class ContactUsDetailsView(DetailView):
    model = ContactUs
    template_name = 'contactus_details.html'
    success_url = reverse_lazy('currency:contactus-list')


class SourceCreateView(CreateView):
    model = Source
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:source-list')


class SourceUpdateView(UpdateView):
    model = Source
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:source-list')


class SourceDeleteView(DeleteView):
    model = Source
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source-list')


class SourceDetailsView(DetailView):
    model = Source
    template_name = 'source_details.html'
    success_url = reverse_lazy('currency:source-list')


class SourceListView(FilterView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'
    filterset_class = SourceFilter
    paginate_by = 25

app/currency/templates/contactUs.html
{% extends "base.html" %}
{% block title %}ContactUs{% endblock title %}
{% block content %}
    <div class="row">
        {% include 'includes/filter.html' %}
    </div>
    <h1>Contact Us List</h1>
    <table border="1">
        <thead>
        <tr>
            <th>Contact ID</th>
            <th>Email From</th>
            <th>Subject</th>
            <th>Message</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for contact in object_list %}
            <tr>
                <td>{{ contact.contact_id }}</td>
                <td>{{ contact.email_from }}</td>
                <td>{{ contact.subject }}</td>
                <td>{{ contact.message }}</td>

                <td>
                    <a href="{% url 'currency:contactus-update' contact.contact_id %}">Edit</a>
                    <a href="{% url 'currency:contactus-delete' contact.contact_id %}">Delete</a>
                    <a href="{% url 'currency:contactus-details' contact.contact_id %}">Detail</a>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>
{% endblock %}

app/currency/templates/contactus_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Contact Us{% endblock title %}

{% block content %}
    <h1>Contact Us</h1>
    <form method="post">

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>

    </form>


{% endblock content %}
```

app/currency/templates/contactus_delete.html
{% extends "base.html" %}

{% block title %}Delete Contact Us{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>You want to delete Contact Us with id {{ contactus.contact_id}}? </h1>
    <form method="post">

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Delete</button>

    </form>


{% endblock content %}
```

app/currency/templates/contactus_details.html
{% extends "base.html" %}

{% block title %}Contact Us Details{% endblock title %}

{% block content %}
    <h1>Contact Us Details</h1>
    <form>

        <li><a>Source mail: {{ contactus.email_from }}</a></li>
        <li><a>Subject:     {{ contactus.subject }}</a></li>
        <br>
        <a>Message: {{ contactus.message }}</a>



    </form>


{% endblock content %}
```

app/currency/templates/contactus_update.html
{% extends "base.html" %}

{% block title %}Update Contact Us{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Update Contact Us</h1>
    <form method="post">

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>

    </form>


{% endblock content %}
```

app/currency/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock title %}


{% block content %}

    Welcome to Currency App!

{% endblock content %}

app/currency/templates/rate_create.html
{% extends "base.html" %}

{% block title %}Create rate{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Create rate</h1>
    <form method="post">

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>

    </form>


{% endblock content %}
```

app/currency/templates/rate_delete.html
{% extends "base.html" %}

{% block title %}Delete source{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>You want to delete Rate with id {{ rate.id}}? </h1>
    <form method="post">

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Delete</button>

    </form>


{% endblock content %}
```

app/currency/templates/rate_list.html
{% extends "base.html" %}
{% block title %}Rate list{% endblock title %}
{% block content %}
   <div class="row">

            {% include 'includes/filter.html' %}

    </div>

    <h1>Rates</h1>
    <a class="btn btn-primary" href="{% url 'currency:rate-create' %}" role="button">Create rate</a>
    <br>
    <br>
    <div class="row">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Buy</th>
                <th>Sell</th>
                <th>Created</th>
                <th>Currency</th>
                <th>Source</th>
                <th>Actions</th>

            </tr>
            </thead>
            <tbody>
            {% for rate in page_obj %}
                <tr>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.sell }}</td>
                    <td>{{ rate.created }}</td>
                    <td>{{ rate.get_currency_type_display }}</td>
                    <td>{{ rate.source }}</td>
                    <td>
                        {% if request.user.is_superuser %}
                            <div class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-expanded="false">
                                Actions
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Edit</a>
                                <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                                <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>

                            </div>
                        {% elif request.user.is_authenticated %}
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                                   data-toggle="dropdown" aria-expanded="false">
                                    Actions
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item"
                                       href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                </div>
                            </div>

                        {% endif %}
                        </div>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>
{% endblock %}

app/currency/templates/rate_update.html
{% extends "base.html" %}

{% block title %}Update rate{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Update rate</h1>
    <form method="post">

        {% csrf_token %}
       {{ form|crispy }}
        <button type="submit">Submit</button>

    </form>


{% endblock content %}
```

app/currency/templates/source_create.html
{% extends "base.html" %}

{% block title %}Create source{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Create source</h1>


    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>

    </form>


{% endblock content %}
```

app/currency/templates/source_details.html
{% extends "base.html" %}

{% block title %}Create source{% endblock title %}

{% block content %}
    <h1>Create source</h1>
    <form>

        <li><a>Source name: {{ source.source_name }}</a></li>
        <br>
        <a>Source URL: {{ source.source_url }} </a>
        <br>
        <img style="height: 100px; width: 100px" src="{{ source.logo_url }}" alt="Logo" >



    </form>


{% endblock content %}
```

app/currency/templates/source_list.html
{% extends "base.html" %}

{% block title %} Source list {% endblock title %}

{% block content %}
    <div class="row">

        {% include 'includes/filter.html' %}

    </div>
    <h1>Source list</h1>

    <button><a href="{% url 'currency:source-create' %}">Create Source</a></button>
    <br>
    <br>

    {% for source in object_list %}
        <a>{{ source.source_name }}</a>
        <a href="{% url 'currency:source-update' source.id %}">Edit</a>
        <a href="{% url 'currency:source-delete' source.id %}">Delete</a>
        <a href="{% url 'currency:source-details' source.id %}">Details</a>
        <br>
    {% endfor %}
    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>

{% endblock content %}
```

app/currency/templates/source_update.html
{% extends "base.html" %}

{% block title %}Update source{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Update source</h1>
    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}
       {{ form|crispy }}
        <button type="submit">Submit</button>

    </form>


{% endblock content %}
```